/* Aura — shared interface strings. View-specific strings live next to their view. */
(function (root) {
  const I = root.Aura.i18n;
  I.add({
    'app.name': ['Aura', 'Aura'],
    'nav.aria': ['Huvudmeny', 'Main menu'],
    'tab.now': ['Nu', 'Now'],
    'tab.day': ['Min dag', 'My day'],
    'tab.capture': ['Fånga', 'Capture'],
    'tab.captureLong': ['Fånga något — skriv eller tala', 'Capture something — type or speak'],
    'tab.aura': ['Aura', 'Aura'],
    'tab.life': ['Livet', 'Life'],

    'a.back': ['Tillbaka', 'Back'],
    'a.close': ['Stäng', 'Close'],
    'a.cancel': ['Avbryt', 'Cancel'],
    'a.confirm': ['Ja', 'Yes'],
    'a.save': ['Spara', 'Save'],
    'a.add': ['Lägg till', 'Add'],
    'a.undo': ['Ångra', 'Undo'],
    'a.done': ['Klart', 'Done'],
    'a.edit': ['Ändra', 'Edit'],
    'a.delete': ['Ta bort', 'Delete'],
    'a.more': ['Mer', 'More'],
    'a.show': ['Visa', 'Show'],
    'a.hide': ['Dölj', 'Hide'],
    'a.skip': ['Hoppa över', 'Skip'],
    'a.next': ['Nästa', 'Next'],
    'a.stop': ['Stoppa', 'Stop'],
    'a.tryAgain': ['Försök igen', 'Try again'],
    'a.doneX': ['Markera {title} som klar', 'Mark {title} as done'],
    'a.reopenX': ['Markera {title} som inte klar', 'Mark {title} as not done'],
    'a.open': ['Öppna', 'Open'],
    'a.notNow': ['Inte nu', 'Not now'],
    'a.noThanks': ['Nej tack', 'No thanks'],
    'a.dictate': ['Tala in', 'Speak'],
    'a.listening': ['Lyssnar … tryck för att sluta', 'Listening … tap to stop'],

    'toast.changes': ['{n} ändring gjord|{n} ändringar gjorda', '{n} change made|{n} changes made'],
    'toast.nothing': ['Inget att ändra — det kan redan vara gjort.', 'Nothing to change — it may already be done.'],
    'toast.undone': ['Ångrat.', 'Undone.'],
    'toast.error': ['Något gick fel. Inget ändrades.', 'Something went wrong. Nothing was changed.'],
    'toast.remote': ['Uppdaterat från en annan enhet.', 'Updated from another device.'],
    'toast.copied': ['Kopierat.', 'Copied.'],

    'meta.overdue': ['skulle varit klart {when}', 'was due {when}'],
    'meta.dueToday': ['klart i dag', 'due today'],
    'meta.due': ['klart {when}', 'due {when}'],
    'meta.carried': ['från tidigare', 'carried over'],
    'meta.for': ['till {name}', 'for {name}'],
    'meta.background': ['sköter sig själv', 'runs by itself'],
    'meta.waitingOn': ['väntar på {who}', 'waiting on {who}'],

    'band.aria': ['Dagen från {from} till {to}', 'The day from {from} to {to}'],
    'greet.morning': ['God morgon', 'Good morning'],
    'greet.day': ['Hej', 'Hello'],
    'greet.afternoon': ['God eftermiddag', 'Good afternoon'],
    'greet.evening': ['God kväll', 'Good evening'],
    'greet.night': ['Sent nu', "It's late"],

    'voice.denied': ['Mikrofonen är inte tillgänglig här. Använd tangentbordets mikrofonknapp i stället — Aura förstår dikterad text på samma sätt.', "The microphone isn't available here. Use your keyboard's microphone button instead — Aura understands dictated text the same way."],
    'voice.none': ['Röstinmatning finns inte i den här webbläsaren. Tangentbordets mikrofon fungerar lika bra.', "Voice input isn't available in this browser. Your keyboard's microphone works just as well."],
    'voice.silence': ['Hörde inget. Försök igen, eller skriv.', "Didn't hear anything. Try again, or type."],
  });
})(typeof globalThis !== 'undefined' ? globalThis : this);
