import {
  FOUNDER_OFFER,
  FOUNDER_PROOF_ACCEPTANCE,
  OUTREACH_FRAMEWORK,
  PAYMENT_READINESS,
  PROSPECT_RUBRIC,
} from './playbooks.mjs';

export const COMPANY_ROLES = Object.freeze([
  {
    id: 'chief-of-staff',
    name: 'Chief of Staff / Project Lead',
    agentId: 'orchestrator',
    remit: 'Keeps one commercial mission active, sequences work and escalates only irreversible CEO decisions.',
    authority: 'May create and reprioritize internal tasks. May not spend, contact customers or approve legal terms.',
    prompt: [
      'You are the Chief of Staff for a founder-led AI software company.',
      'The CEO is the user. ChatGPT is the project manager. Your job is to turn the current revenue mission into a short, evidence-driven execution sequence.',
      'Protect the company from infrastructure theatre, idea hopping and premature coding.',
      'Return: current bottleneck, three ordered actions, owner-only decision if any, and a stop condition.',
    ].join(' '),
  },
  {
    id: 'market-intelligence',
    name: 'Market Intelligence Lead',
    agentId: 'growth-hacker',
    remit: 'Finds current buyer evidence, competitors, pricing, reachable segments and distribution paths.',
    authority: 'May research and draft evidence. May not claim demand without sources or direct buyer signals.',
    prompt: [
      'You are the Market Intelligence Lead.',
      'Separate facts, inferences and unknowns. Prefer current primary evidence and observable buyer behaviour.',
      'Do not brainstorm unrelated businesses. Evaluate the active mission and identify the fastest falsifiable test.',
      'Return: evidence table, strongest counter-evidence, reachable buyer definition, and recommended next test.',
    ].join(' '),
  },
  {
    id: 'customer-discovery',
    name: 'Customer Discovery Lead',
    agentId: 'reality-checker',
    remit: 'Converts assumptions into interview questions, outreach hypotheses and buying-signal criteria.',
    authority: 'May prepare customer conversations. Actual outreach requires the CEO gate.',
    prompt: [
      'You are the Customer Discovery Lead.',
      'Design discovery that distinguishes politeness from payment intent. Never count likes, compliments or vague interest as validation.',
      'Return: five high-signal questions, disqualifiers, what counts as a buying signal, and the minimum sample before a decision.',
    ].join(' '),
  },
  {
    id: 'offer-pricing',
    name: 'Offer & Pricing Lead',
    agentId: 'growth-hacker',
    remit: 'Freezes a narrow founder offer, price, guarantee, exclusions and checkout copy.',
    authority: 'May draft and test offers. Price changes beyond the current hypothesis require CEO approval.',
    prompt: [
      'You are the Offer & Pricing Lead.',
      'Package a concrete outcome, not AI features. Keep scope narrow enough for manual founder delivery.',
      'Return: one-sentence offer, deliverables, exclusions, price logic, risk reversal and checkout copy.',
    ].join(' '),
  },
  {
    id: 'sales-distribution',
    name: 'Sales & Distribution Lead',
    agentId: 'content-creator',
    remit: 'Builds prospect lists, personalization angles, outreach drafts and follow-up sequences.',
    authority: 'May prepare drafts and queues. May not send messages or publish without CEO approval.',
    prompt: [
      'You are the Sales & Distribution Lead.',
      'Optimize for direct, qualified conversations and first payment—not follower growth.',
      'Avoid spam, generic mass outreach and unsupported personalization.',
      'Return: prospect qualification rule, outreach draft, follow-up cadence and measurable conversion target.',
    ].join(' '),
  },
  {
    id: 'product-engineering',
    name: 'Product Engineering Lead',
    agentId: 'rapid-prototyper',
    remit: 'Builds only the smallest proof or fulfillment tooling required by a paid test.',
    authority: 'May create internal prototypes after the commercial gate. Full product work requires paid validation.',
    prompt: [
      'You are the Product Engineering Lead.',
      'No full SaaS, infrastructure expansion or speculative feature work before payment evidence.',
      'Prefer manual fulfillment plus small utilities. Define acceptance tests before implementation.',
      'Return: minimum proof, acceptance criteria, build/no-build recommendation and estimated operational burden.',
    ].join(' '),
  },
  {
    id: 'qa-red-team',
    name: 'QA & Red Team Lead',
    agentId: 'reality-checker',
    remit: 'Attempts to disprove demand, differentiation, delivery quality and production readiness.',
    authority: 'May block promotion to the next gate. Cannot approve based on model opinion alone.',
    prompt: [
      'You are the QA & Red Team Lead. Default verdict is NEEDS WORK.',
      'Attack the buyer assumption, alternative solutions, willingness to pay, quality, operational cost and legal risk.',
      'State exactly what evidence would change the verdict. Never approve on vibes.',
      'Return: verdict, top failure modes, required evidence, and kill recommendation.',
    ].join(' '),
  },
  {
    id: 'finance-risk',
    name: 'Finance & Risk Lead',
    agentId: 'reality-checker',
    remit: 'Tracks payment readiness, margins, refunds, costs, tax/compliance questions and downside caps.',
    authority: 'May prepare checklists. Banking, identity, binding legal acceptance and spending remain CEO-only.',
    prompt: [
      'You are the Finance & Risk Lead for a Swedish founder selling globally.',
      'Do not provide invented legal certainty. Mark items requiring current professional or official verification.',
      'Return: payment-readiness checklist, unit economics, cost ceiling, refund exposure and owner-only actions.',
    ].join(' '),
  },
  {
    id: 'customer-success',
    name: 'Customer Success Lead',
    agentId: 'content-creator',
    remit: 'Defines onboarding, delivery communication, acceptance and testimonial/referral capture.',
    authority: 'May draft templates. Refunds, promises and public use of customer work require CEO approval.',
    prompt: [
      'You are the Customer Success Lead.',
      'Design a low-support founder delivery that makes the promised outcome obvious and measurable.',
      'Return: onboarding questions, delivery checklist, acceptance request, support boundaries and referral/testimonial ask.',
    ].join(' '),
  },
]);

const now = '2026-08-21T06:00:00.000Z';

export function buildDefaultState() {
  return {
    version: 1,
    company: {
      name: 'Founder Revenue Company',
      objective: 'Maximize legitimate real income as quickly as possible with AI-assisted delivery, while protecting cash and avoiding speculative builds.',
      ceo: 'Jonatan',
      projectManager: 'ChatGPT',
      operatingRule: 'One active revenue mission. Evidence before code. Payment before scale.',
      ownerOnly: [
        'Identity verification, BankID and 2FA',
        'Banking and payment-account approval',
        'Binding legal acceptance',
        'Spending money or changing financial exposure',
        'Sending customer outreach or publishing under the owner’s identity',
        'Final brand, offer, price and irreversible product decisions',
      ],
    },
    automation: {
      enabled: false,
      dailyRunLimit: 6,
      allowExternalActions: false,
      lastRunAt: null,
      note: 'Internal analysis only. Outreach, publishing, spending and legal acceptance are permanently human-gated.',
    },
    roles: COMPANY_ROLES,
    missions: [
      {
        id: 'mission-release-pack',
        name: 'Music Performance Release Pack',
        brand: 'Separate global brand — name pending CEO approval',
        thesis: 'Independent performance creators will pay for a local-first workflow that turns one finished musical performance into a small set of musically coherent, publishable release assets.',
        buyer: 'Independent guitarists, instrumentalists and performance creators who already publish finished long-form performances and use Shorts, Reels or TikTok.',
        problem: 'Generic clippers optimize speech hooks and virality heuristics; music performers still spend time finding phrase boundaries, preserving musical coherence, reframing instruments and packaging each release.',
        offer: 'One finished performance in → two musically coherent vertical clips, one thumbnail/cover, titles/descriptions/hashtags and an upload-ready release folder.',
        priceCents: 2900,
        currency: 'USD',
        priceLadder: ['$29 one release', '$99 five releases', '$179 twelve releases', 'No subscription initially', 'Credits do not expire'],
        primaryChannel: 'Direct founder outreach to 30 qualified global performance creators; English language; no existing audience assumed.',
        stage: 'offer',
        status: 'active',
        scoreInput: {
          painIntensity: 4,
          buyerReachability: 4,
          evidenceQuality: 3,
          timeToFirstPayment: 4,
          manualFulfillability: 5,
          differentiation: 4,
          assetLeverage: 5,
          riskProfile: 4,
        },
        hardGates: {
          buyerIdentified: true,
          painEvidence: true,
          reachableProspects: true,
          manualFulfillment: true,
          proofReady: false,
          paymentReady: false,
          noBuildBeforeSale: true,
          legalManageable: true,
        },
        fatalRisks: [],
        competitionRisk: 'Broad AI clippers already sell long-video-to-shorts automation cheaply. The offer fails if customers see no meaningful advantage in music-aware selection, framing and release packaging.',
        nextAction: 'Finish one real founder proof and make the legitimate $29 payment path live; then seek payment from the first ten qualified prospects before building SaaS.',
        ownerDecision: 'CEO approval is required for final separate brand, final offer copy and first outreach send.',
        grillReports: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    tasks: [
      {
        id: 'task-proof-spec',
        missionId: 'mission-release-pack',
        roleId: 'qa-red-team',
        title: 'Freeze the founder-proof acceptance test',
        definitionOfDone: 'A pass/fail checklist for two vertical clips, cover, metadata and upload-ready folder, including musical phrase integrity and instrument framing.',
        priority: 1,
        status: 'done',
        executionMode: 'internal',
        output: FOUNDER_PROOF_ACCEPTANCE,
        error: '',
        completedAt: now,
        execution: { source: 'project-manager-seed', agentId: 'ChatGPT', model: 'GPT-5.6 Pro' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-proof-build',
        missionId: 'mission-release-pack',
        roleId: 'product-engineering',
        title: 'Produce one real customer-grade founder proof',
        definitionOfDone: 'Use an existing finished performance to produce the complete promised pack and record actual hands-on fulfillment time.',
        priority: 2,
        status: 'blocked',
        executionMode: 'human',
        blockedBy: 'Requires the owner’s real source video/audio and local production files.',
        output: FOUNDER_PROOF_ACCEPTANCE,
        error: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-offer-freeze',
        missionId: 'mission-release-pack',
        roleId: 'offer-pricing',
        title: 'Draft and structurally freeze founder offer and checkout copy',
        definitionOfDone: 'English one-page offer with exact deliverables, exclusions, $29 price, turnaround, revision boundary and call to action.',
        priority: 3,
        status: 'done',
        executionMode: 'internal',
        output: FOUNDER_OFFER,
        error: '',
        completedAt: now,
        execution: { source: 'project-manager-seed', agentId: 'ChatGPT', model: 'GPT-5.6 Pro' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-payment',
        missionId: 'mission-release-pack',
        roleId: 'finance-risk',
        title: 'Make the first legitimate international $29 payment path live',
        definitionOfDone: 'A buyer can pay $29 and receive a clear receipt/order confirmation; owner has completed unavoidable verification.',
        priority: 4,
        status: 'blocked',
        executionMode: 'human',
        blockedBy: 'Identity, banking, BankID/2FA or binding account acceptance must be completed by the CEO.',
        output: PAYMENT_READINESS,
        error: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-prospect-rubric',
        missionId: 'mission-release-pack',
        roleId: 'market-intelligence',
        title: 'Lock the 30-prospect qualification rubric',
        definitionOfDone: 'Objective inclusion/exclusion rules based on recent long-form music performance publishing, short-form activity and public contactability.',
        priority: 5,
        status: 'done',
        executionMode: 'internal',
        output: PROSPECT_RUBRIC,
        error: '',
        completedAt: now,
        execution: { source: 'project-manager-seed', agentId: 'ChatGPT', model: 'GPT-5.6 Pro' },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-intake-delivery',
        missionId: 'mission-release-pack',
        roleId: 'customer-success',
        title: 'Build the founder intake and delivery package',
        definitionOfDone: 'A minimal English intake form, source-file handoff instructions, delivery email, acceptance request and support boundary consistent with the founder offer.',
        priority: 6,
        status: 'queued',
        executionMode: 'internal',
        output: '',
        error: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-offer-redteam',
        missionId: 'mission-release-pack',
        roleId: 'qa-red-team',
        title: 'Red-team the founder offer before CEO approval',
        definitionOfDone: 'A TEST/KILL/GO verdict focused on musical quality, rights, support burden, revisions, refunds, differentiation and the cheapest remaining falsification tests.',
        priority: 7,
        status: 'queued',
        executionMode: 'internal',
        output: '',
        error: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-outreach-drafts',
        missionId: 'mission-release-pack',
        roleId: 'sales-distribution',
        title: 'Prepare ten genuinely personalized founder offers',
        definitionOfDone: 'Ten drafts tied to specific public performances and a single relevant benefit, with no invented details and one follow-up each.',
        priority: 8,
        status: 'blocked',
        executionMode: 'internal',
        blockedBy: 'Requires ten actual 8/10-qualified prospects and their cited public performances; generic drafts are prohibited.',
        output: OUTREACH_FRAMEWORK,
        error: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-ceo-approve',
        missionId: 'mission-release-pack',
        roleId: 'chief-of-staff',
        title: 'CEO gate: approve brand, offer and first outreach batch',
        definitionOfDone: 'CEO records an explicit approval or rejection with any required correction.',
        priority: 9,
        status: 'blocked',
        executionMode: 'human',
        blockedBy: 'Owner-only commercial decision.',
        output: '',
        error: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-send-outreach',
        missionId: 'mission-release-pack',
        roleId: 'sales-distribution',
        title: 'Send the first ten founder offers and log outcomes',
        definitionOfDone: 'Ten approved messages sent through legitimate channels; each contact and response is logged.',
        priority: 10,
        status: 'blocked',
        executionMode: 'external',
        blockedBy: 'External communication is never automated without explicit CEO approval.',
        output: '',
        error: '',
        createdAt: now,
        updatedAt: now,
      },
    ],
    events: [],
    audit: [
      {
        id: 'audit-seed',
        at: now,
        type: 'system',
        title: 'Revenue OS initialized',
        detail: 'Primary mission locked to Music Performance Release Pack. General clipper and speculative SaaS build are excluded. Acceptance test, founder offer and prospect rubric are preloaded as completed work products.',
        status: 'ok',
      },
    ],
  };
}
