import {
  FOUNDER_OFFER,
  FOUNDER_PROOF_ACCEPTANCE,
  OUTREACH_FRAMEWORK,
  PAYMENT_READINESS,
  PROSPECT_RUBRIC,
} from './playbooks.mjs';

function role(id, name, agentId, remit, authority, prompt) {
  return Object.freeze({ id, name, agentId, remit, authority, prompt });
}

export const COMPANY_ROLES = Object.freeze([
  role(
    'chief-of-staff',
    'Chief of Staff / Project Lead',
    'orchestrator',
    'Keeps one revenue mission active, sequences work and escalates irreversible CEO decisions.',
    'May create and reprioritize internal tasks. May not spend, contact customers or accept terms.',
    'Act as Chief of Staff. Prevent idea hopping and infrastructure theatre. Return the bottleneck, three ordered actions, one owner-only decision if unavoidable, and a stop condition.',
  ),
  role(
    'market-intelligence',
    'Market Intelligence Lead',
    'growth-hacker',
    'Finds sourced buyer evidence, qualified companies, relevant procurements, alternatives and channels.',
    'May research and draft evidence. May not claim demand without sources or direct buyer signals.',
    'Evaluate only BidSprint 48. Separate facts, inferences and unknowns. Return source links, counter-evidence, qualified-buyer records and the fastest falsifiable test.',
  ),
  role(
    'customer-discovery',
    'Customer Discovery Lead',
    'reality-checker',
    'Turns assumptions into high-signal questions and payment-intent criteria.',
    'May prepare conversations. Actual contact requires the CEO gate.',
    'Distinguish politeness from payment intent. Return high-signal questions, disqualifiers, buying signals and the minimum decision sample.',
  ),
  role(
    'offer-pricing',
    'Offer & Pricing Lead',
    'growth-hacker',
    'Maintains the narrow offer, price, exclusions and checkout wording.',
    'May refine copy. Any price or scope change beyond the approved pilot requires CEO approval.',
    'Package a concrete decision and control outcome, not AI features. Protect the 48-hour boundary, exclusions and manual fulfillability.',
  ),
  role(
    'sales-distribution',
    'Sales & Distribution Lead',
    'content-creator',
    'Builds sourced prospect records, personalization and follow-up drafts.',
    'May prepare drafts and queues. May not send or publish without CEO approval.',
    'Optimize for first payment. Never guess emails, buy lists, fabricate procurement links or use generic mass outreach.',
  ),
  role(
    'product-engineering',
    'Delivery Engineering Lead',
    'rapid-prototyper',
    'Builds customer-grade proof and only the smallest fulfillment utilities required by paid pilots.',
    'May create internal proofs. Full product work requires three unrelated paid deliveries.',
    'Prefer source-traced manual delivery plus small utilities. Define acceptance tests first and report actual operational burden.',
  ),
  role(
    'qa-red-team',
    'QA & Red Team Lead',
    'reality-checker',
    'Attempts to disprove demand, source accuracy, delivery quality and economics.',
    'May block a gate. Cannot approve based on model opinion alone.',
    'Default to NEEDS WORK. Attack buyer trust, willingness to pay, missed requirements, legal boundary, 48-hour feasibility and support burden. Return GO/TEST/KILL and explicit evidence needed.',
  ),
  role(
    'finance-risk',
    'Finance & Risk Lead',
    'reality-checker',
    'Tracks contracting, payment readiness, margins, refunds, tax/compliance questions and downside caps.',
    'May prepare checklists. Identity, banking, terms and spending remain CEO-only.',
    'Use Frilans Finans as the approved first route and Cool Company only as reserve. Do not invent legal or tax certainty. Return owner-only actions and cost/refund exposure.',
  ),
  role(
    'customer-success',
    'Customer Success Lead',
    'content-creator',
    'Defines onboarding, delivery communication, acceptance and testimonial capture.',
    'May draft templates. Refunds, promises and public use of customer work require CEO approval.',
    'Design a low-support 48-hour delivery that makes the decision, source trail, assumptions and remaining customer actions obvious.',
  ),
]);

const now = '2026-08-21T07:08:14.000Z';

function task({
  id,
  roleId,
  title,
  definitionOfDone,
  priority,
  status,
  executionMode,
  output = '',
  blockedBy = '',
  completedAt,
  execution,
}) {
  return {
    id,
    missionId: 'mission-bidsprint-48',
    roleId,
    title,
    definitionOfDone,
    priority,
    status,
    executionMode,
    ...(blockedBy ? { blockedBy } : {}),
    output,
    error: '',
    ...(completedAt ? { completedAt } : {}),
    ...(execution ? { execution } : {}),
    createdAt: now,
    updatedAt: now,
  };
}

export function buildDefaultState() {
  const seededExecution = {
    source: 'project-manager-seed',
    agentId: 'ChatGPT',
    model: 'GPT-5.6 Pro',
  };

  return {
    version: 2,
    company: {
      name: 'Founder Revenue Company',
      objective: 'Maximize legitimate real income quickly with AI-assisted delivery while protecting cash and avoiding speculative builds.',
      ceo: 'Jonatan',
      projectManager: 'ChatGPT',
      operatingRule: 'One active revenue mission. Evidence before code. Payment before scale.',
      ownerOnly: [
        'Identity verification, BankID and 2FA',
        'Banking, self-employment-company and payment-account approval',
        'Binding legal acceptance',
        'Spending money or changing financial exposure',
        'Sending customer outreach or publishing under the owner’s identity',
        'Final price changes and irreversible product decisions',
      ],
    },
    automation: {
      enabled: true,
      dailyRunLimit: 4,
      allowExternalActions: false,
      lastRunAt: null,
      note: 'Internal work is enabled. Outreach, publishing, spending, contracting and legal acceptance remain human-gated.',
    },
    roles: COMPANY_ROLES,
    missions: [
      {
        id: 'mission-bidsprint-48',
        name: 'BidSprint 48',
        brand: 'BidSprint 48 — CEO approved',
        thesis: 'Swedish service companies will pay for a rapid, source-traced go/no-go decision because a bad tender consumes scarce bid time and one missed mandatory requirement can invalidate the effort.',
        buyer: 'Swedish SMEs and service suppliers with documented public-sector or procurement activity, especially owner-led firms or companies without dedicated bid capacity.',
        problem: 'They must quickly decide whether a public procurement is worth pursuing while identifying mandatory requirements, missing evidence, deadlines and administrative risks.',
        offer: 'Within 48 hours after complete input and confirmed start, deliver a source-traced go/avstå recommendation, requirement matrix, evidence gaps, deadline/question/responsibility calendar, bid-structure skeleton and pre-submission recheck list for one public procurement.',
        priceCents: 190000,
        currency: 'SEK',
        priceLadder: [
          'Founder pilot: 1,900 SEK excluding VAT, paid upfront',
          'Post-pilot pricing requires payment evidence and CEO approval',
        ],
        primaryChannel: 'Source-backed direct outreach through each company’s legitimate public business contact route. First batch: 10 CEO-approved prospects from a 30-company evidence list. No guessed personal emails or bought lists.',
        stage: 'presell',
        status: 'active',
        scoreInput: {
          painIntensity: 4,
          buyerReachability: 4,
          evidenceQuality: 4,
          timeToFirstPayment: 4,
          manualFulfillability: 5,
          differentiation: 4,
          assetLeverage: 4,
          riskProfile: 2,
        },
        hardGates: {
          buyerIdentified: true,
          painEvidence: true,
          reachableProspects: false,
          manualFulfillment: true,
          proofReady: false,
          paymentReady: false,
          noBuildBeforeSale: true,
          legalManageable: true,
        },
        fatalRisks: [],
        competitionRisk: 'A buyer may use internal bid staff, specialist procurement consultants or free self-review. The pilot fails if source accuracy and trust are not visibly stronger than a quick internal scan, or if 1,900 SEK cannot support reliable 48-hour fulfillment.',
        nextAction: 'Complete one customer-grade source-traced sample, finish the 30-prospect evidence list and make the Frilans Finans contracting path operational; then present the first ten exact messages for CEO approval.',
        ownerDecision: 'Brand, offer and 1,900 SEK pilot are approved. CEO action remains required for self-employment-company verification and the exact first outreach send.',
        grillReports: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    tasks: [
      task({
        id: 'task-proof-spec',
        roleId: 'qa-red-team',
        title: 'Freeze the BidSprint 48 proof acceptance test',
        definitionOfDone: 'A pass/fail standard for source tracing, mandatory-requirement coverage, go/avstå logic, deadlines, evidence gaps, legal boundary and fulfillment time.',
        priority: 0,
        status: 'done',
        executionMode: 'internal',
        output: FOUNDER_PROOF_ACCEPTANCE,
        completedAt: now,
        execution: seededExecution,
      }),
      task({
        id: 'task-proof-build',
        roleId: 'product-engineering',
        title: 'Build one customer-grade BidSprint 48 sample',
        definitionOfDone: 'Select a suitable official Swedish procurement, capture every source document, produce the full anonymized deliverable, run the acceptance test and record hands-on time. Never invent company evidence.',
        priority: 1,
        status: 'queued',
        executionMode: 'internal',
      }),
      task({
        id: 'task-prospect-list',
        roleId: 'market-intelligence',
        title: 'Complete the 30-company source-backed prospect list',
        definitionOfDone: 'Thirty Swedish service companies with name, org.nr, website, public business contact route, sourced service fit, sourced procurement connection, relevant procurement and 10-point score. Preserve job reference job-0371e9a776 where available.',
        priority: 2,
        status: 'queued',
        executionMode: 'internal',
        output: PROSPECT_RUBRIC,
      }),
      task({
        id: 'task-intake-delivery',
        roleId: 'customer-success',
        title: 'Build the customer intake and delivery package',
        definitionOfDone: 'Swedish intake questions, document handoff instructions, 48-hour start confirmation, delivery message, acceptance request, data-handling note and support boundary.',
        priority: 3,
        status: 'queued',
        executionMode: 'internal',
      }),
      task({
        id: 'task-offer-redteam',
        roleId: 'qa-red-team',
        title: 'Run the BidSprint 48 commercial and delivery grill',
        definitionOfDone: 'GO/TEST/KILL verdict covering buyer trust, 1,900 SEK economics, source completeness, missed-requirement risk, legal boundary, 48-hour feasibility, competition and kill conditions.',
        priority: 4,
        status: 'queued',
        executionMode: 'internal',
      }),
      task({
        id: 'task-offer-freeze',
        roleId: 'offer-pricing',
        title: 'Freeze the approved BidSprint 48 founder offer',
        definitionOfDone: 'Swedish one-page offer with deliverables, exclusions, 1,900 SEK excluding VAT, upfront payment, 48-hour start rule, correction boundary and CTA.',
        priority: 5,
        status: 'done',
        executionMode: 'internal',
        output: FOUNDER_OFFER,
        completedAt: now,
        execution: { ...seededExecution, source: 'ceo-approved-seed' },
      }),
      task({
        id: 'task-payment',
        roleId: 'finance-risk',
        title: 'Make the legitimate Swedish B2B contracting path live',
        definitionOfDone: 'Frilans Finans is the confirmed contracting party, or Cool Company is explicitly selected as reserve; a customer can legitimately accept and pay 1,900 SEK excluding VAT before work begins.',
        priority: 6,
        status: 'blocked',
        executionMode: 'human',
        blockedBy: 'Requires CEO identity verification, BankID/2FA, payout details and binding acceptance with the self-employment company.',
        output: PAYMENT_READINESS,
      }),
      task({
        id: 'task-outreach-drafts',
        roleId: 'sales-distribution',
        title: 'Prepare the first ten source-backed BidSprint 48 messages',
        definitionOfDone: 'Ten drafts tied to ten 8/10-qualified companies and specific procurement evidence, with no invented contact data and one follow-up each.',
        priority: 7,
        status: 'blocked',
        executionMode: 'internal',
        blockedBy: 'Requires the completed proof, legitimate payment path and first ten qualified prospect records.',
        output: OUTREACH_FRAMEWORK,
      }),
      task({
        id: 'task-ceo-approve',
        roleId: 'chief-of-staff',
        title: 'CEO gate: approve the exact first outreach batch',
        definitionOfDone: 'CEO approves or rejects the ten exact messages and confirms the contracting/payment path.',
        priority: 8,
        status: 'blocked',
        executionMode: 'human',
        blockedBy: 'Owner-only external communication and contracting decision.',
      }),
      task({
        id: 'task-send-outreach',
        roleId: 'sales-distribution',
        title: 'Send the first ten approved BidSprint 48 offers and log outcomes',
        definitionOfDone: 'Ten approved messages are sent through legitimate public business channels; each contact and response is logged accurately.',
        priority: 9,
        status: 'blocked',
        executionMode: 'external',
        blockedBy: 'External communication is never automated without explicit CEO approval of the exact batch.',
      }),
    ],
    events: [],
    audit: [
      {
        id: 'audit-seed-bidsprint-48',
        at: now,
        type: 'system',
        title: 'Revenue OS initialized with CEO-approved BidSprint 48',
        detail: 'BidSprint 48 is the single active mission. The 1,900 SEK pilot, Swedish public-procurement buyer and 48-hour decision/control deliverable are locked. Internal automation is enabled; outreach, contracting and payment verification remain CEO-gated.',
        status: 'ok',
      },
    ],
  };
}
